/**
 * Mobile (Capacitor) environment.
 *
 * The Android WebView serves files from `capacitor://localhost`, which
 * cannot reach a relative `/api` URL. The mobile build MUST therefore
 * point at an absolute `apiUrl` of the deployed API.
 *
 * AUTO-GENERATED by scripts/set-env.mjs when .env is present.
 */
export const environment = {
  production: true,
  supabaseUrl: '',
  supabaseAnonKey: '',
  apiUrl: '',
};
