/**
 * Production (web) environment.
 *
 * `apiUrl` is empty by default to use a same-origin /api path. Override
 * via PUBLIC_API_URL in .env if the API is hosted on a different domain.
 *
 * AUTO-GENERATED by scripts/set-env.mjs when .env is present.
 */
export const environment = {
  production: true,
  supabaseUrl: '',
  supabaseAnonKey: '',
  apiUrl: '',
};
