#!/usr/bin/env node
/**
 * scripts/set-env.mjs
 *
 * Generates `src/environments/environment.ts`, `environment.prod.ts` and
 * `environment.mobile.ts` from values defined in `.env`.
 *
 * Usage:
 *   node scripts/set-env.mjs                 # uses ./.env
 *   node scripts/set-env.mjs --target=mobile # only refresh the mobile env
 *
 * Rules:
 *  - Only PUBLIC_* variables end up in the frontend bundle.
 *  - Missing variables are written as empty strings; a warning is printed.
 *  - The generated files are listed in .gitignore — they are derived
 *    artifacts, the source of truth is `.env`.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const ENV_FILE = resolve(ROOT, '.env');
const ENV_DIR = resolve(ROOT, 'src/environments');

const args = process.argv.slice(2);
const targetArg = args.find((a) => a.startsWith('--target='));
const target = targetArg ? targetArg.split('=')[1] : 'all';

/** Tiny, dependency-free .env parser (KEY=VALUE, # comments, quoted values). */
function parseEnv(content) {
  const out = {};
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let val = line.slice(eq + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}

const env = existsSync(ENV_FILE)
  ? parseEnv(readFileSync(ENV_FILE, 'utf-8'))
  : {};

if (!existsSync(ENV_FILE)) {
  console.warn('[set-env] .env not found. Generated files will use empty values.');
}

function read(key) {
  const v = env[key] ?? process.env[key] ?? '';
  if (!v) console.warn(`[set-env] missing ${key}`);
  return v;
}

const PUBLIC_SUPABASE_URL = read('PUBLIC_SUPABASE_URL') || read('SUPABASE_URL');
const PUBLIC_SUPABASE_ANON_KEY =
  read('PUBLIC_SUPABASE_ANON_KEY') || read('SUPABASE_ANON_KEY');
const PUBLIC_API_URL = read('PUBLIC_API_URL');

/** Render an environment.ts file. */
function render({ production, apiUrl }) {
  return `// AUTO-GENERATED by scripts/set-env.mjs — do not edit by hand.
export const environment = {
  production: ${production},
  supabaseUrl: ${JSON.stringify(PUBLIC_SUPABASE_URL)},
  supabaseAnonKey: ${JSON.stringify(PUBLIC_SUPABASE_ANON_KEY)},
  apiUrl: ${JSON.stringify(apiUrl)},
};
`;
}

const targets = {
  dev: {
    file: resolve(ENV_DIR, 'environment.ts'),
    content: render({ production: false, apiUrl: PUBLIC_API_URL || '' }),
  },
  prod: {
    file: resolve(ENV_DIR, 'environment.prod.ts'),
    content: render({ production: true, apiUrl: PUBLIC_API_URL || '' }),
  },
  mobile: {
    file: resolve(ENV_DIR, 'environment.mobile.ts'),
    // Mobile build always needs an absolute API URL — the webview cannot
    // reach a relative `/api` path on capacitor://localhost.
    content: render({ production: true, apiUrl: PUBLIC_API_URL || '' }),
  },
};

const selected =
  target === 'all' ? Object.keys(targets) : target.split(',').map((t) => t.trim());

for (const key of selected) {
  const t = targets[key];
  if (!t) {
    console.error(`[set-env] unknown target: ${key}`);
    process.exit(1);
  }
  writeFileSync(t.file, t.content);
  console.log(`[set-env] wrote ${t.file}`);
}

if (target === 'mobile' && !PUBLIC_API_URL) {
  console.error(
    '[set-env] PUBLIC_API_URL is required for the mobile target — the APK cannot reach a relative URL.'
  );
  process.exit(1);
}
